apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls
  namespace: maratea
spec:
  secretName: app-tls
  dnsNames:
    - app.staging.betaserver.ru
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

