apiVersion: v1
kind: Secret
metadata:
  name: s3-backup-secret
  namespace: maratea
type: Opaque
stringData:
  # Замените на ваши реальные credentials Timeweb S3
  S3_ENDPOINT: "s3.twcstorage.ru"
  S3_ACCESS_KEY: "CNHJ6SLS6KZDWJYA7Z0R"
  S3_SECRET_KEY: "ju6TjDzEVJrDqOe26o8CxiAK1JF3yBsarzOWZS3t"
  S3_BUCKET: "af0d31be-cb217873-8a91-4500-9782-12793c7d715d"
  S3_REGION: "ru-1"

